/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import access.signupPage;
import java.sql.SQLException;
/**
 *
 * @author galang
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        akunButton = new javax.swing.JButton();
        riwayatButton2 = new javax.swing.JButton();
        statusButton1 = new javax.swing.JButton();
        statusButton2 = new javax.swing.JButton();
        statusButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(242, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(42, 98, 154));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        akunButton.setBackground(new java.awt.Color(42, 98, 154));
        akunButton.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        akunButton.setForeground(new java.awt.Color(255, 255, 255));
        akunButton.setText("Layanan");
        akunButton.setAlignmentY(1.0F);
        akunButton.setBorderPainted(false);
        akunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akunButtonActionPerformed(evt);
            }
        });
        jPanel2.add(akunButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, 20));

        riwayatButton2.setBackground(new java.awt.Color(42, 98, 154));
        riwayatButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        riwayatButton2.setForeground(new java.awt.Color(255, 255, 255));
        riwayatButton2.setText("Kontak");
        riwayatButton2.setAlignmentY(1.0F);
        riwayatButton2.setBorderPainted(false);
        riwayatButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(riwayatButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 20));

        statusButton1.setBackground(new java.awt.Color(42, 98, 154));
        statusButton1.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton1.setForeground(new java.awt.Color(255, 255, 255));
        statusButton1.setText("Beranda");
        statusButton1.setAlignmentY(1.0F);
        statusButton1.setBorderPainted(false);
        statusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(statusButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 20));

        statusButton2.setBackground(new java.awt.Color(242, 255, 255));
        statusButton2.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton2.setForeground(new java.awt.Color(42, 97, 153));
        statusButton2.setText("Login");
        statusButton2.setAlignmentY(1.0F);
        statusButton2.setBorderPainted(false);
        statusButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(statusButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 70, 20));

        statusButton3.setBackground(new java.awt.Color(242, 255, 255));
        statusButton3.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton3.setForeground(new java.awt.Color(42, 97, 153));
        statusButton3.setText("Sign Up");
        statusButton3.setAlignmentY(1.0F);
        statusButton3.setBorderPainted(false);
        statusButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(statusButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 90, 20));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/logo.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 68));

        jLabel4.setBackground(new java.awt.Color(42, 98, 154));
        jLabel4.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(42, 98, 154));
        jLabel4.setText("WiseWash Solusinya...");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 303, 33));

        jLabel5.setBackground(new java.awt.Color(42, 98, 154));
        jLabel5.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(42, 98, 154));
        jLabel5.setText("Mau Laundry Anti Ribet?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 33));

        jLabel6.setBackground(new java.awt.Color(42, 98, 154));
        jLabel6.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(42, 98, 154));
        jLabel6.setText("Rapi dan Bersih Setiap Hari");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 303, 21));

        jLabel7.setBackground(new java.awt.Color(42, 98, 154));
        jLabel7.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(42, 98, 154));
        jLabel7.setText("Kepuasan Anda Prioritas Kami");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 303, 14));

        statusButton.setBackground(new java.awt.Color(42, 98, 154));
        statusButton.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        statusButton.setForeground(new java.awt.Color(255, 255, 255));
        statusButton.setText("Pesan Sekarang");
        statusButton.setAlignmentY(1.0F);
        statusButton.setBorderPainted(false);
        statusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusButtonActionPerformed(evt);
            }
        });
        jPanel1.add(statusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 37));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 153, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Foto/gambar_1.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 290, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton2ActionPerformed
        // TODO add your handling code here:
        try {
            dispose();
            loginPage halamanLogin = new loginPage();
            halamanLogin.setVisible(true);
        } catch (SQLException e) {
            // Tangani pengecualian di sini, misalnya mencetak stack trace
            e.printStackTrace();
        }
    }//GEN-LAST:event_statusButton2ActionPerformed

    private void statusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButtonActionPerformed
        // TODO add your handling code here:
        try {
            dispose();
            loginPage halamanLogin = new loginPage();
            halamanLogin.setVisible(true);
        } catch (SQLException e) {
            // Tangani pengecualian di sini, misalnya mencetak stack trace
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_statusButtonActionPerformed

    private void statusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusButton1ActionPerformed

    private void riwayatButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_riwayatButton2ActionPerformed

    private void akunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akunButtonActionPerformed

    }//GEN-LAST:event_akunButtonActionPerformed

    private void statusButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusButton3ActionPerformed
        // TODO add your handling code here:
        try {
            dispose();
            signupPage halamanSignup = new signupPage();
            halamanSignup.setVisible(true);
        } catch (SQLException e) {
            // Tangani pengecualian di sini, misalnya mencetak stack trace
            e.printStackTrace();
        }
    }//GEN-LAST:event_statusButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akunButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton riwayatButton2;
    private javax.swing.JButton statusButton;
    private javax.swing.JButton statusButton1;
    private javax.swing.JButton statusButton2;
    private javax.swing.JButton statusButton3;
    // End of variables declaration//GEN-END:variables
}
